### ISSUE TITLE
Patch on Facebook app x86 version

### ISSUE THREAD

**Issue by dhanh** [pouyadarabi/Facebook_SSL_Pinning#1]
Hi Pouya Darabi,

Thank you so much on your effort to create a patch for Facebook app. I'm trying to follow your step to patch the Facebook app x86 version, to run it on BlueStack. Unfortunately I got no luck as I have very little knowledge on ASM. Could you please help me to patch the version x86 to?

Thanks in advance.

**Comment by pouyadarabi** [comment]
Hi,

I will try to install an x86 android and patch lib file

**Comment by verysimplenick** [comment]
@pouyadarabi any progress?

**Comment by verysimplenick** [comment]
I tried same edition for x86, (ver 134) but get error `SSLHandshake: Received fatal alert: unknown_ca` :(

```c
char __cdecl proxygen::SSLVerification::verifyWithMetrics(int a1, int a2, int a3, int a4, int a5, int a6, int a7)
{
  char result; // al@3

  if ( a2 || a6 )
  {
    X509_STORE_CTX_get_error_depth(a2);
    result = 1;
  }
  else
  {
    result = verifyWithMetrics_2(0, a3, a4, 0, a7);
  }
  return result;
}
```
@pouyadarabi Maybe you get me pseudocode how it's works now?
p.s. tried always return true, it's not helps too

**Comment by pouyadarabi** [comment]
I create another patch for **[X86](https://github.com/pouyadarabi/Facebook_SSL_Pinning/tree/master/x86)** version
tested on **Android x86 4.3**

**Comment by verysimplenick** [comment]
@pouyadarabi thanks 👍
