### ISSUE TITLE
messenger

### ISSUE THREAD

**Issue by mSharif10** [pouyadarabi/Facebook_SSL_Pinning#15]
the app always crashes saying **"messenger is not responding"** please what can I do??

**Comment by tuanngokien** [comment]
I solved by closing messenger completely before patching

**Comment by mSharif10** [comment]
but is it worked? I mean **intercepting its traffic?**

**Comment by tuanngokien** [comment]
This messenger version looks obsolete, you should find another way

**Comment by mSharif10** [comment]
What another way?!

**Comment by oliverbytes** [comment]
Does this mean it's also possible to Unpin the SSL of Messenger? Do you guys have the link to the instruction?
