### ISSUE TITLE
Facebook Android 202.0.0.40.99 & Messenger 196.0.0.29.99 x86 - Patch method not work

### ISSUE THREAD

**Issue by dhanh** [pouyadarabi/Facebook_SSL_Pinning#16]
Hi,

I'm trying to patch the Facebook for Android & Messenger x86 but it seem like the old method not work any more. I tried to modify method "...verifyWithMetrics..." but the patched app not connect under proxy. 

Do you have any idea, could you give another new version ?

Thanks in advanced.

**Comment by oliverbytes** [comment]
Do you know where I can find the instruction link please?

**Comment by dhanh** [comment]
Sorry, it seem the old instruction link got deleted, I cannot search any such guide like it.
