### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by ghost** [pouyadarabi/Facebook_SSL_Pinning#18]
Here is My Environment : 
-My Device is Running Android Oreo 8.1.0 [Rooted], Oneplus 5T.
-Custom CA Certificate Installed, Unpacked the apk and modified the manifest to Trust the User CA Certificate.
-Replaced the libcoldstart.so [arm]
-Using Burp proxy to intercept
-Checked whether i'm able to intercept the https connections [Chrome Browser][Working]
-app crashed on the startup 
-Checke the logcat, but couldnt able to identify the issues 

Do any one faced the same problem ??

**Comment by n0nvme** [comment]
same problem
Samsung galaxy J1, android 4.4.4 rooted

**Comment by n0nvme** [comment]
You need to chmod and chown new file

**Comment by theumairahmed** [comment]
I don't think that Step 2 is mandatory or is it?
I can sniff the traffic successfully only by replacing the libcoldstart.so file. Please enlighten me more.
