### ISSUE TITLE
154.0.0.33.385 arm not working?

### ISSUE THREAD

**Issue by larsovski** [pouyadarabi/Facebook_SSL_Pinning#2]
Tried to appy latest available version on a real phone (arm). 
Forgot to change owner and permissions on the file which caused an error when running the app first, after chown and chmod it works w/o using a proxy, but as soon as I proxy the connection it stops any network traffic just like the unpatched app.

What am I missing?

Steps taken: downloaded latest APK (January 11, 2018), installed it, run it once, closed it, replaced libcoldstart in /data/data/com.facebook.katana/lib-xzs, chmod and chown the file, run app again

**Comment by knife-s** [comment]
Which proxy are you using and which android version?
I recommend charles for this, also, make sure you have installed the SSL certificate for your proxy (this mechanism changes in Android 7+)

**Comment by larsovski** [comment]
Proxy (Fiddler) works fine with other apps (pinning removed, too). Android is 4.4.2

**Comment by ghost** [comment]
It's will be wonderful if you make a patch for Facebook Messenger. Thank you in advanced!
