### ISSUE TITLE
It seems does not work anymore

### ISSUE THREAD

**Issue by dimmduh** [pouyadarabi/Facebook_SSL_Pinning#6]
It works some limited time - when first launch app - enter password and ... end
facebook shows "changing language" and it seems restart app
Hmm... seems facebook checks and downloads update automatically.

**Comment by dimmduh** [comment]
Changed device language to english, reinstall the app - and it seems solved.

**Comment by dimmduh** [comment]
sorry, the issue is still here - facebook update self after some time (10-20 minutes).
Google play updates disabled.

**Comment by pouyadarabi** [comment]
use latest patch
