### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by PATAPOsha** [pouyadarabi/Facebook_SSL_Pinning#7]
Worked fine couple of days, on the next day charles failed to decode trafic. Looks like fb app self-apdated and replaced cracked libcoldstart.so. I tried again replacing the file, but after that fb-app keeps constantly crashing.

**Comment by PATAPOsha** [comment]
Forgot to set chmod after replacing... Still works fine...

**Comment by tiavx** [comment]
Is the solution still working? I'm getting the error "Client SSL handshake failed - no cipher suites in common" using Charles Proxy and I can't use the application.
